name: text_to_image_gen
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.4+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  brain_fusion: ^0.0.7
  lottie: ^2.3.2
  url_launcher: ^6.1.10
  sentry_flutter: ^7.5.1
  iconsax: ^0.0.8
  shared_preferences: ^2.1.0
  flex_color_scheme: ^7.0.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Aesthetic
      fonts:
        - asset: assets/fonts/Aesthetic-Regular.ttf
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa-Heavy.ttf
    - family: NexaLight
      fonts:
        - asset: assets/fonts/Nexa-ExtraLight.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          style: normal
